### ISSUE TITLE
Compare two exiting Roles

### ISSUE THREAD

**Issue by AvnerCohen** [apono-io/weed#1]
Thanks for making weed!
I am actually not 100% sure my use case makes sense, if it's not, feel free to just close it.

I am facing a situation where a complex operation works with one Role, but doesn't work with another.
Each role has 20~ policies.
What I want is to basically compare the two roles, so the diff is between one role to another, and not between one role to a policy file.
I am guessing this may mean building a policy file on the fly or something, not sure.

**Comment by ofir76** [comment]
Hey Avner!
This definitely can be solved using Weed.

Please follow the progress of the linked Pull Request.
